[tool.poetry]
name = "moonrush"
version = "0.1.0"
description = "A basic UNIX-based command parser."
authors = ["eeriemyxi <eeriemyxi@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
